language: node_js
node_js:
  - "8"

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --prefer-offline
  - yarn global add codecov --prefer-offline

script:
  - set -e
  - yarn lint
  - yarn test
  - codecov
  - yarn build
  - yarn dts

deploy:
  provider: npm
  email: abi@hafs.in
  api_key: $NPM_KEY
  skip_cleanup: true
  on:
    tags: true
