language: node_js
node_js:
  - "6"

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --prefer-offline
  - yarn global add codecov --prefer-offline

script:
  - yarn lint
  - yarn test
  - codecov
  - yarn build

deploy:
  provider: npm
  email: abi@hafs.in
  api_key: $NPM_KEY
  on:
    tags: true
