// Generated by dts-bundle v0.7.3

declare module 'samwell' {
    import { Logger } from 'samwell/lib/logger';
    const _default: Logger;
    export default _default;
}

declare module 'samwell/lib/logger' {
    export interface ILogItemContext {
        [name: string]: any;
        err?: Error | INormalizedError;
    }
    export interface INormalizedError {
        name: string;
        message: string;
        stack: string[];
    }
    export type LogFunction = (...args: any[]) => void;
    export interface ILogItem {
        time: Date;
        level: string;
        msg: string;
        context?: ILogItemContext | null;
    }
    export type Writer = (log: ILogItem) => void;
    export class Logger {
        debug: LogFunction;
        info: LogFunction;
        warn: LogFunction;
        error: LogFunction;
        writer: Writer;
        baseContext?: ILogItemContext;
        constructor(baseContext: ILogItemContext | undefined, writer: Writer);
        createChild(context: ILogItemContext): Logger;
    }
}

declare module 'samwell/register-server' {
  export default undefined;
}
